name: CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run test:ci

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: coverage

      - name: Report summary
        if: success()
        run: |
          if [ -f coverage/coverage-summary.json ]; then
            lines=$(jq '.total.lines.pct' coverage/coverage-summary.json)
            statements=$(jq '.total.statements.pct' coverage/coverage-summary.json)
            branches=$(jq '.total.branches.pct' coverage/coverage-summary.json)
            functions=$(jq '.total.functions.pct' coverage/coverage-summary.json)
            echo "### Coverage Summary" >> $GITHUB_STEP_SUMMARY
            echo "Lines: $lines%" >> $GITHUB_STEP_SUMMARY
            echo "Statements: $statements%" >> $GITHUB_STEP_SUMMARY
            echo "Branches: $branches%" >> $GITHUB_STEP_SUMMARY
            echo "Functions: $functions%" >> $GITHUB_STEP_SUMMARY
          fi
